### ISSUE TITLE
LICENSE有误

### ISSUE THREAD

**Issue by AmeroHan** [Hicircum/SC-Generator#1]
萌娘百科文本内容使用的协议为[署名-非商业性使用-相同方式共享 3.0中国大陆](https://creativecommons.org/licenses/by-nc-sa/3.0/cn/legalcode)，衍生自其的内容应当采用相同协议。

**Comment by AmeroHan** [comment]
参考：
- [萌娘百科:著作权信息](https://zh.moegirl.org.cn/_?curid=89)
- [Creative Commons对署名-非商业性使用-相同方式共享 3.0 中国大陆（CC BY-NC-SA 3.0 CN）的简要说明](https://creativecommons.org/licenses/by-nc-sa/3.0/cn/)

**Comment by Hicircum** [comment]
感谢指正，license已修改完毕
